```
name: "RetroAssembly"
version: "1.0.13"
slug: "retroassembly"
description: "The personal retro game collection cabinet in your browser."
url: "https://github.com/arianrhodsandlot/retroassembly"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
init: false
map:
  - config:rw
  - share:rw
  - media:rw

ports:
  8000/tcp: 8099

ingress: false
schema:
  port: port
```
