name: "RetroAssembly"
version: "1.0.0"
slug: "retroassembly"
description: "The personal retro game collection cabinet in your browser."
url: "https://github.com/arianrhodsandlot/retroassembly"
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 8099
map:
  - config:rw
  - media:rw
options:
  port: 8000
schema:
  port: port
image: "ha-retroassembly-{arch}"
startup: application
